# Generated by Django 4.0 on 2021-12-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='board',
            new_name='my_board',
        ),
    ]
